filebeat.version: 9.0.4

# Filebeat inputs - collect logs from containers and files
filebeat.inputs:
- type: container
  enabled: true
  paths:
    - '/var/lib/docker/containers/*/*.log'
  fields:
    log_type: container_logs
    environment: development
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - '/var/log/*.log'
  fields:
    log_type: system_logs
    environment: development
  fields_under_root: true

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]

# Disable Elasticsearch output (since we're using Logstash)
output.elasticsearch:
  enabled: false

# Kibana configuration
setup.kibana:
  host: "kibana:5601"

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Processors
processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~

# Disable template loading since Logstash handles it
setup.template.enabled: false
setup.ilm.enabled: false
